model:
  _target_: model.VAE
  latent_dim: 64

optimizer:
  _target_: torch.optim.Adam
  lr: 0.001
  weight_decay: 1e-5

datamodule:
  _target_: datamodule.CelebA

  data_dir: ~/GANS/homework/2-GAN/celeba
  batch_size: 32
  num_workers: 16
  train_transforms:
    RandomRotation:
      degrees: 10
    RandomHorizontalFlip:
      p: 0.5
    Resize:
      size: [64, 64]
    ToTensor: {}


  val_transforms:
    RandomRotation:
      degrees: 10
    RandomHorizontalFlip:
      p: 0.5
    Resize:
      size: [64, 64]
    ToTensor: {}

trainer:
  gpus: [3]
  accelerator: ddp
  log_every_n_steps: 20

logger:
  project: test

checkpoint: {}
